// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__SSL_ROBOT_PROTOCOL_H__
#define __BITPROTO__SSL_ROBOT_PROTOCOL_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Timestamp in milliseconds (uint32 covers ~49 days at 1ms resolution)
typedef uint32_t Timestamp; // 32bit

// Scaled position: millimeters from origin (range ±32.767 m)
typedef int16_t PositionScaled; // 16bit

// Scaled angle: 0.01 degree per unit (range ±327.67°)
typedef int16_t AngleScaled; // 16bit

// Scaled linear velocity: 1 mm/s per unit (range ±32.767 m/s)
typedef int16_t LinearVelocityScaled; // 16bit

// Scaled angular velocity: 0.01 rad/s per unit (range ±327.67 rad/s)
typedef int16_t AngularVelocityScaled; // 16bit

// Maximum valid robot ID (11 robots: IDs 0–10)
#define ROBOT_ID_MAX 10

// Broadcast address — all robots execute, none reply
#define ROBOT_ID_BROADCAST 15

// Motion command from base station to a specific robot or broadcast
#define MSG_TYPE_COMMAND 0

// Configuration command (set ID, run calibration, etc.)
#define MSG_TYPE_CONFIG 1

// Telemetry response from robot back to base station
#define MSG_TYPE_TELEMETRY 2

// Assign a new robot ID (new ID provided in robot_id field of RobotConfig)
#define CONFIG_FLAG_SET_ID 1

// Trigger the wheel encoder calibration routine on the robot
#define CONFIG_FLAG_RUN_CALIBRATION 2

// Trigger magnetometer calibration only
#define CONFIG_FLAG_CALIBRATE_MAG 4

// Reset all NVS-stored configuration to factory defaults
#define CONFIG_FLAG_RESET_NVS 8

// Full NVS erase — all namespaces, all keys
#define CONFIG_FLAG_FACTORY_RESET 16

// Bit 0:  Communication loss with base station
#define ERROR_COMM_LOSS 1

// Bit 1:  IMU failure
#define ERROR_IMU_FAIL 2

// Bit 2:  TOF sensor failure
#define ERROR_TOF_FAIL 4

// Bit 3:  Battery undervoltage
#define ERROR_BATT_UNDERVOLT 8

// Bit 4:  Battery overvoltage
#define ERROR_BATT_OVERVOLT 16

// Bit 5:  Kicker capacitor not charging
#define ERROR_KICKER_NO_CHARGE 32

// Bit 6:  Encoder reading invalid (any encoder)
#define ERROR_ENCODER_INVALID 64

// Bit 7:  Temperature warning
#define ERROR_TEMPERATURE_WARN 128

// Bit 8:  Motor 0 fault
#define ERROR_MOTOR0_FAULT 256

// Bit 9:  Motor 1 fault
#define ERROR_MOTOR1_FAULT 512

// Bit 10: Motor 2 fault
#define ERROR_MOTOR2_FAULT 1024

// Bit 11: Motor 3 fault
#define ERROR_MOTOR3_FAULT 2048

// Number of bytes to encode struct Header
#define BYTES_LENGTH_HEADER 5

// ---------------------------------------------------------------------------
// Header message, defines the msg type, robot ID and timestamp
// ---------------------------------------------------------------------------
struct Header {
    uint8_t msg_type; // 4bit
    // Message type (e.g. MSG_TYPE_COMMAND)
    uint8_t robot_id; // 4bit
    // Target robot ID or ROBOT_ID_BROADCAST
    Timestamp timestamp; // 32bit
};

// Number of bytes to encode struct Pose
#define BYTES_LENGTH_POSE 12

struct Pose {
    PositionScaled x; // 16bit
    // X coordinate (mm)
    PositionScaled y; // 16bit
    // Y coordinate (mm)
    AngleScaled angle; // 16bit
    // Orientation (0.01°)
    LinearVelocityScaled x_v; // 16bit
    // Linear velocity in X (mm/s)
    LinearVelocityScaled y_v; // 16bit
    // Linear velocity in Y (mm/s)
    AngularVelocityScaled angular_vel; // 16bit
};

// Number of bytes to encode struct RobotCommand
#define BYTES_LENGTH_ROBOT_COMMAND 30

// ---------------------------------------------------------------------------
// RobotCommand — base station → robot (unicast or broadcast)
// First byte is msg_type; robot peeks it to demux before full decode.
// Broadcast (robot_id == ROBOT_ID_BROADCAST): execute, do NOT reply.
// Unicast: execute and reply with RobotTelemetry.
// 
// Size: 5 (Header) + 12 (target_pose) + 12 (vision_pose) + 1 (kick_velocity) = 30 bytes  ✓
// ---------------------------------------------------------------------------
struct RobotCommand {
    struct Header header; // 40bit
    // Message header (msg_type, robot_id, timestamp)
    struct Pose target_pose; // 96bit
    // Desired pose / velocity setpoint
    struct Pose vision_pose; // 96bit
    // Current pose from vision system
    uint8_t kick_velocity; // 8bit
};

// Number of bytes to encode struct RobotConfig
#define BYTES_LENGTH_ROBOT_CONFIG 8

// ---------------------------------------------------------------------------
// RobotConfig — base station → robot (always unicast; no reply expected)
// Use config_flags bitmask to select operation(s); param carries auxiliary value.
// 
// Size: 5 (Header) + 1 (config_flags) + 2 (param) = 8 bytes  ✓
// ---------------------------------------------------------------------------
struct RobotConfig {
    struct Header header; // 40bit
    // Message header (msg_type, robot_id, timestamp)
    uint8_t config_flags; // 8bit
    // Bitmask of CONFIG_FLAG_* constants
    uint16_t param; // 16bit
};

// Number of bytes to encode struct RobotTelemetry
#define BYTES_LENGTH_ROBOT_TELEMETRY 22

// ---------------------------------------------------------------------------
// RobotTelemetry — robot → base station (reply to unicast RobotCommand only)
// 
// Size: 5 (Header) + 12 (robot_pose) + 1 (battery_percentage) + 2 (kicker_voltage) + 2 (error_flags) = 22 bytes  ✓
// ---------------------------------------------------------------------------
struct RobotTelemetry {
    struct Header header; // 40bit
    // Message header (msg_type, robot_id, timestamp)
    struct Pose robot_pose; // 96bit
    // Current estimated pose
    uint8_t battery_percentage; // 8bit
    // 0–100 %
    uint16_t kicker_voltage; // 16bit
    // Voltage in 0.01 V units (e.g. 1650 = 16.50 V)
    uint16_t error_flags; // 16bit
};

// Encode struct Header to given buffer s.
int EncodeHeader(struct Header *m, unsigned char *s);
// Decode struct Header from given buffer s.
int DecodeHeader(struct Header *m, unsigned char *s);
// Format struct Header to a json format string.
int JsonHeader(struct Header *m, char *s);

// Encode struct Pose to given buffer s.
int EncodePose(struct Pose *m, unsigned char *s);
// Decode struct Pose from given buffer s.
int DecodePose(struct Pose *m, unsigned char *s);
// Format struct Pose to a json format string.
int JsonPose(struct Pose *m, char *s);

// Encode struct RobotCommand to given buffer s.
int EncodeRobotCommand(struct RobotCommand *m, unsigned char *s);
// Decode struct RobotCommand from given buffer s.
int DecodeRobotCommand(struct RobotCommand *m, unsigned char *s);
// Format struct RobotCommand to a json format string.
int JsonRobotCommand(struct RobotCommand *m, char *s);

// Encode struct RobotConfig to given buffer s.
int EncodeRobotConfig(struct RobotConfig *m, unsigned char *s);
// Decode struct RobotConfig from given buffer s.
int DecodeRobotConfig(struct RobotConfig *m, unsigned char *s);
// Format struct RobotConfig to a json format string.
int JsonRobotConfig(struct RobotConfig *m, char *s);

// Encode struct RobotTelemetry to given buffer s.
int EncodeRobotTelemetry(struct RobotTelemetry *m, unsigned char *s);
// Decode struct RobotTelemetry from given buffer s.
int DecodeRobotTelemetry(struct RobotTelemetry *m, unsigned char *s);
// Format struct RobotTelemetry to a json format string.
int JsonRobotTelemetry(struct RobotTelemetry *m, char *s);

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPositionScaled(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPositionScaled(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessAngleScaled(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatAngleScaled(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessLinearVelocityScaled(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatLinearVelocityScaled(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessAngularVelocityScaled(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatAngularVelocityScaled(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessHeader(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatHeader(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPose(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPose(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessRobotCommand(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatRobotCommand(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessRobotConfig(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatRobotConfig(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessRobotTelemetry(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatRobotTelemetry(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif