// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "oxebots_interfaces/ssl_robot_protocol_bp.h"

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpUint(32, sizeof(uint32_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpUint(32, sizeof(uint32_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessPositionScaled(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatPositionScaled(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessAngleScaled(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatAngleScaled(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessLinearVelocityScaled(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatLinearVelocityScaled(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessAngularVelocityScaled(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatAngularVelocityScaled(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(16, sizeof(int16_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitHeader(struct Header *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->msg_type), BpUint(4, sizeof(uint8_t)), "msg_type");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->robot_id), BpUint(4, sizeof(uint8_t)), "robot_id");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->timestamp), BpAlias(32, sizeof(Timestamp), BpXXXProcessTimestamp, BpXXXJsonFormatTimestamp, BP_TYPE_UINT), "timestamp");
}

void BpXXXProcessHeader(void *data, struct BpProcessorContext *ctx) {
    struct Header *m = (struct Header *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 40, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatHeader(void *data, struct BpJsonFormatContext *ctx) {
    struct Header *m = (struct Header *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 40, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeHeader(struct Header *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessHeader((void *)m, &ctx);
    return 0;
}

int DecodeHeader(struct Header *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessHeader((void *)m, &ctx);
    return 0;
}

int JsonHeader(struct Header *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatHeader((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPose(struct Pose *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->x), BpAlias(16, sizeof(PositionScaled), BpXXXProcessPositionScaled, BpXXXJsonFormatPositionScaled, BP_TYPE_INT), "x");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->y), BpAlias(16, sizeof(PositionScaled), BpXXXProcessPositionScaled, BpXXXJsonFormatPositionScaled, BP_TYPE_INT), "y");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->angle), BpAlias(16, sizeof(AngleScaled), BpXXXProcessAngleScaled, BpXXXJsonFormatAngleScaled, BP_TYPE_INT), "angle");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->x_v), BpAlias(16, sizeof(LinearVelocityScaled), BpXXXProcessLinearVelocityScaled, BpXXXJsonFormatLinearVelocityScaled, BP_TYPE_INT), "x_v");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->y_v), BpAlias(16, sizeof(LinearVelocityScaled), BpXXXProcessLinearVelocityScaled, BpXXXJsonFormatLinearVelocityScaled, BP_TYPE_INT), "y_v");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->angular_vel), BpAlias(16, sizeof(AngularVelocityScaled), BpXXXProcessAngularVelocityScaled, BpXXXJsonFormatAngularVelocityScaled, BP_TYPE_INT), "angular_vel");
}

void BpXXXProcessPose(void *data, struct BpProcessorContext *ctx) {
    struct Pose *m = (struct Pose *)(data);
    struct BpMessageFieldDescriptor field_descriptors[6];
    BpFieldDescriptorsInitPose(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 6, 96, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPose(void *data, struct BpJsonFormatContext *ctx) {
    struct Pose *m = (struct Pose *)(data);
    struct BpMessageFieldDescriptor field_descriptors[6];
    BpFieldDescriptorsInitPose(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 6, 96, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePose(struct Pose *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPose((void *)m, &ctx);
    return 0;
}

int DecodePose(struct Pose *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPose((void *)m, &ctx);
    return 0;
}

int JsonPose(struct Pose *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPose((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitRobotCommand(struct RobotCommand *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->header), BpMessage(40, sizeof(struct Header), BpXXXProcessHeader, BpXXXJsonFormatHeader), "header");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->target_pose), BpMessage(96, sizeof(struct Pose), BpXXXProcessPose, BpXXXJsonFormatPose), "target_pose");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->vision_pose), BpMessage(96, sizeof(struct Pose), BpXXXProcessPose, BpXXXJsonFormatPose), "vision_pose");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->kick_velocity), BpUint(8, sizeof(uint8_t)), "kick_velocity");
}

void BpXXXProcessRobotCommand(void *data, struct BpProcessorContext *ctx) {
    struct RobotCommand *m = (struct RobotCommand *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitRobotCommand(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 240, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatRobotCommand(void *data, struct BpJsonFormatContext *ctx) {
    struct RobotCommand *m = (struct RobotCommand *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitRobotCommand(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 240, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeRobotCommand(struct RobotCommand *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessRobotCommand((void *)m, &ctx);
    return 0;
}

int DecodeRobotCommand(struct RobotCommand *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessRobotCommand((void *)m, &ctx);
    return 0;
}

int JsonRobotCommand(struct RobotCommand *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatRobotCommand((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitRobotConfig(struct RobotConfig *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->header), BpMessage(40, sizeof(struct Header), BpXXXProcessHeader, BpXXXJsonFormatHeader), "header");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->config_flags), BpUint(8, sizeof(uint8_t)), "config_flags");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->param), BpUint(16, sizeof(uint16_t)), "param");
}

void BpXXXProcessRobotConfig(void *data, struct BpProcessorContext *ctx) {
    struct RobotConfig *m = (struct RobotConfig *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitRobotConfig(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 64, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatRobotConfig(void *data, struct BpJsonFormatContext *ctx) {
    struct RobotConfig *m = (struct RobotConfig *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitRobotConfig(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 64, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeRobotConfig(struct RobotConfig *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessRobotConfig((void *)m, &ctx);
    return 0;
}

int DecodeRobotConfig(struct RobotConfig *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessRobotConfig((void *)m, &ctx);
    return 0;
}

int JsonRobotConfig(struct RobotConfig *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatRobotConfig((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitRobotTelemetry(struct RobotTelemetry *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->header), BpMessage(40, sizeof(struct Header), BpXXXProcessHeader, BpXXXJsonFormatHeader), "header");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->robot_pose), BpMessage(96, sizeof(struct Pose), BpXXXProcessPose, BpXXXJsonFormatPose), "robot_pose");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->battery_percentage), BpUint(8, sizeof(uint8_t)), "battery_percentage");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->kicker_voltage), BpUint(16, sizeof(uint16_t)), "kicker_voltage");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->error_flags), BpUint(16, sizeof(uint16_t)), "error_flags");
}

void BpXXXProcessRobotTelemetry(void *data, struct BpProcessorContext *ctx) {
    struct RobotTelemetry *m = (struct RobotTelemetry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitRobotTelemetry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 176, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatRobotTelemetry(void *data, struct BpJsonFormatContext *ctx) {
    struct RobotTelemetry *m = (struct RobotTelemetry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitRobotTelemetry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 176, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeRobotTelemetry(struct RobotTelemetry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessRobotTelemetry((void *)m, &ctx);
    return 0;
}

int DecodeRobotTelemetry(struct RobotTelemetry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessRobotTelemetry((void *)m, &ctx);
    return 0;
}

int JsonRobotTelemetry(struct RobotTelemetry *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatRobotTelemetry((void *)m, &ctx);
    return ctx.n;
}